# Rumpus - A 1970s-inspired Helix color theme
# https://github.com/715d/rumpus

# UI Elements
"ui.background" = { bg = "walnut" }
"ui.text" = "almond"
"ui.text.focus" = { fg = "light-harvest-gold", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "cork" }
"ui.text.info" = "denim-blue"
"ui.cursor" = { fg = "walnut", bg = "harvest-gold" }
"ui.cursor.insert" = { fg = "walnut", bg = "avocado-green" }
"ui.cursor.select" = { fg = "walnut", bg = "lava-gold" }
"ui.cursor.match" = { fg = "walnut", bg = "light-denim-blue" }
"ui.cursor.primary" = { fg = "walnut", bg = "harvest-gold" }
"ui.cursor.primary.insert" = { fg = "walnut", bg = "avocado-green" }
"ui.cursor.primary.select" = { fg = "walnut", bg = "lava-gold" }
"ui.selection" = { fg = "walnut", bg = "lava-gold" }
"ui.linenr" = "cork"
"ui.linenr.selected" = { fg = "harvest-gold", modifiers = ["bold"] }
"ui.cursorline" = { bg = "chocolate-brown" }

# Statusline
"ui.statusline" = { fg = "almond", bg = "chocolate-brown" }
"ui.statusline.inactive" = { fg = "light-denim-blue", bg = "chocolate-brown" }
"ui.statusline.normal" = { fg = "walnut", bg = "harvest-gold" }
"ui.statusline.insert" = { fg = "walnut", bg = "avocado-green" }
"ui.statusline.select" = { fg = "walnut", bg = "lava-gold" }
"ui.statusline.separator" = { fg = "chocolate-brown" }

# Bufferline
"ui.bufferline" = { fg = "almond", bg = "chocolate-brown" }
"ui.bufferline.active" = { fg = "walnut", bg = "harvest-gold" }
"ui.bufferline.background" = { bg = "walnut" }

# Popups and menus
"ui.popup" = { fg = "almond", bg = "chocolate-brown" }
"ui.popup.info" = { fg = "almond", bg = "chocolate-brown" }
"ui.window" = { fg = "chocolate-brown" }
"ui.menu" = { fg = "almond", bg = "chocolate-brown" }
"ui.menu.selected" = { fg = "walnut", bg = "harvest-gold" }
"ui.menu.scroll" = { fg = "harvest-gold", bg = "chocolate-brown" }
"ui.help" = { fg = "almond", bg = "chocolate-brown" }

# Virtual elements
"ui.virtual.whitespace" = "cork"
"ui.virtual.ruler" = { bg = "chocolate-brown" }
"ui.virtual.indent-guide" = "cork"
"ui.virtual.inlay-hint" = { fg = "cork" }
"ui.virtual.inlay-hint.parameter" = { fg = "cork" }
"ui.virtual.inlay-hint.type" = { fg = "cork" }
"ui.virtual.wrap" = { fg = "cork" }
"ui.virtual.jump-label" = { fg = "persimmon", modifiers = ["bold"] }

# Gutter
"ui.gutter" = { bg = "walnut" }
"ui.gutter.selected" = { bg = "chocolate-brown" }

# Debug
"ui.debug.breakpoint" = "persimmon"
"ui.debug.active" = "lava-gold"
"ui.highlight" = { bg = "chocolate-brown" }
"ui.highlight.frameline" = { bg = "chocolate-brown" }

# Diagnostics
"error" = "persimmon"
"warning" = "lava-gold"
"info" = "light-denim-blue"
"hint" = "avocado-green"

"diagnostic" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { color = "persimmon", style = "curl" } }
"diagnostic.warning" = { underline = { color = "lava-gold", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-denim-blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "avocado-green", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Syntax highlighting - Comments
"comment" = { fg = "cork", modifiers = ["italic"] }

# Syntax highlighting - Constants
"constant" = "lava-gold"
"constant.builtin" = "light-lava-gold"
"constant.character" = "avocado-green"
"constant.character.escape" = "burnt-orange"
"constant.numeric" = "lava-gold"
"constant.numeric.integer" = "lava-gold"
"constant.numeric.float" = "light-lava-gold"

# Syntax highlighting - Strings
"string" = "avocado-green"
"string.regexp" = "light-avocado"
"string.special" = "burnt-orange"
"string.special.path" = "avocado-green"
"string.special.url" = { fg = "light-denim-blue", underline = { style = "line" } }
"string.special.symbol" = "harvest-gold"

# Syntax highlighting - Numbers and Booleans
"number" = "lava-gold"
"boolean" = "lava-gold"

# Syntax highlighting - Attributes
"attribute" = "light-denim-blue"

# Syntax highlighting - Types
"type" = "light-denim-blue"
"type.builtin" = "denim-blue"
"constructor" = "denim-blue"

# Syntax highlighting - Functions
"function" = "harvest-gold"
"function.builtin" = "light-harvest-gold"
"function.macro" = "burnt-orange"
"function.special" = "burnt-orange"

# Syntax highlighting - Keywords
"keyword" = "burnt-orange"

# Syntax highlighting - Operators
"operator" = "almond"

# Syntax highlighting - Variables
"variable" = "almond"
"variable.parameter" = { fg = "almond", modifiers = ["italic"] }
"variable.builtin" = "light-harvest-gold"
"variable.other" = "almond"
"variable.other.member" = "almond"
"variable.other.member.private" = "almond"

# Syntax highlighting - Labels and Namespaces
"label" = "burnt-orange"
"namespace" = "denim-blue"
"module" = "denim-blue"

# Syntax highlighting - Punctuation
"punctuation" = "almond"
"punctuation.bracket" = "almond"
"punctuation.delimiter" = "almond"
"punctuation.special" = "burnt-orange"

# Syntax highlighting - Special
"special" = "burnt-orange"

# Syntax highlighting - Tags (HTML/XML)
"tag" = "burnt-orange"
"tag.builtin" = "burnt-orange"

# Markup
"markup.heading" = { fg = "burnt-orange", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "burnt-orange", modifiers = ["bold"] }
"markup.list" = "harvest-gold"
"markup.list.unnumbered" = "harvest-gold"
"markup.list.numbered" = "harvest-gold"
"markup.list.checked" = "avocado-green"
"markup.list.unchecked" = "lava-gold"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "light-denim-blue", underline = { style = "line" } }
"markup.link.label" = "avocado-green"
"markup.link.text" = "avocado-green"
"markup.quote" = "avocado-green"
"markup.raw" = "lava-gold"
"markup.raw.inline" = "lava-gold"
"markup.raw.block" = "lava-gold"
"markup.normal.completion" = "almond"
"markup.normal.hover" = "almond"

# Diff
"diff.plus" = "avocado-green"
"diff.plus.gutter" = "avocado-green"
"diff.minus" = "persimmon"
"diff.minus.gutter" = "persimmon"
"diff.delta" = "burnt-orange"
"diff.delta.moved" = "light-denim-blue"
"diff.delta.conflict" = "persimmon"
"diff.delta.gutter" = "burnt-orange"

# Rainbow brackets (optional)
"rainbow.0" = "harvest-gold"
"rainbow.1" = "burnt-orange"
"rainbow.2" = "avocado-green"
"rainbow.3" = "light-denim-blue"
"rainbow.4" = "lava-gold"

[palette]
# Primary colors
walnut = "#2A1810"
chocolate-brown = "#5F3822"
cork = "#98755f"
almond = "#F4DDB3"
harvest-gold = "#E9A131"
burnt-orange = "#F67422"
avocado-green = "#79966d"
denim-blue = "#5B7C99"
lava-gold = "#D3BE47"
persimmon = "#E84A38"

# Light variants (ANSI bright colors)
light-brown = "#84563B"
light-avocado = "#9BB589"
light-harvest-gold = "#F1C760"
light-denim-blue = "#7A96B0"
light-lava-gold = "#E1D36B"
light-almond = "#FCF0DC"
