# Rumpus - A 1970s-inspired Helix color theme
# https://github.com/715d/rumpus

# UI Elements
"ui.background" = { bg = "walnut" }
"ui.text" = "almond"
"ui.text.focus" = { fg = "harvest-gold", modifiers = ["bold"] }
"ui.cursor" = { fg = "walnut", bg = "harvest-gold" }
"ui.cursor.match" = { fg = "walnut", bg = "lava-gold" }
"ui.cursor.primary" = { fg = "walnut", bg = "harvest-gold" }
"ui.selection" = { fg = "walnut", bg = "lava-gold" }
"ui.linenr" = "chocolate-brown"
"ui.linenr.selected" = { fg = "harvest-gold", modifiers = ["bold"] }
"ui.cursorline" = { bg = "chocolate-brown" }

# Statusline
"ui.statusline" = { fg = "almond", bg = "chocolate-brown" }
"ui.statusline.inactive" = { fg = "denim-blue", bg = "chocolate-brown" }
"ui.statusline.normal" = { fg = "walnut", bg = "harvest-gold" }
"ui.statusline.insert" = { fg = "walnut", bg = "avocado-green" }
"ui.statusline.select" = { fg = "walnut", bg = "lava-gold" }

# Popups and menus
"ui.popup" = { fg = "almond", bg = "chocolate-brown" }
"ui.window" = { fg = "chocolate-brown" }
"ui.menu" = { fg = "almond", bg = "chocolate-brown" }
"ui.menu.selected" = { fg = "walnut", bg = "harvest-gold" }
"ui.help" = { fg = "almond", bg = "chocolate-brown" }

# Virtual elements
"ui.virtual.whitespace" = "chocolate-brown"
"ui.virtual.ruler" = { bg = "chocolate-brown" }
"ui.virtual.indent-guide" = "chocolate-brown"

# Gutter
"ui.gutter" = { bg = "walnut" }

# Diagnostics
"error" = "persimmon"
"warning" = "lava-gold"
"info" = "denim-blue"
"hint" = "avocado-green"

"diagnostic.error" = { underline = { color = "persimmon", style = "curl" } }
"diagnostic.warning" = { underline = { color = "lava-gold", style = "curl" } }
"diagnostic.info" = { underline = { color = "denim-blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "avocado-green", style = "curl" } }

# Syntax highlighting
"comment" = { fg = "denim-blue", modifiers = ["italic"] }
"consalmondt" = "lava-gold"
"consalmondt.builtin" = "lava-gold"
"consalmondt.character" = "avocado-green"
"string" = "avocado-green"
"number" = "lava-gold"
"boolean" = "lava-gold"

"attribute" = "denim-blue"
"type" = "harvest-gold"
"type.builtin" = "harvest-gold"
"constructor" = "harvest-gold"

"function" = "denim-blue"
"function.builtin" = "denim-blue"
"function.macro" = "burnt-orange"

"keyword" = "burnt-orange"
"keyword.control" = "burnt-orange"
"keyword.operator" = "burnt-orange"
"operator" = "denim-blue"

"variable" = "almond"
"variable.parameter" = "almond"
"variable.builtin" = "harvest-gold"

"label" = "burnt-orange"
"namespace" = "harvest-gold"

"punctuation" = "almond"
"punctuation.bracket" = "almond"
"punctuation.delimiter" = "almond"

"special" = "burnt-orange"

# Markup
"markup.heading" = { fg = "burnt-orange", modifiers = ["bold"] }
"markup.list" = "harvest-gold"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "denim-blue", underline = { style = "line" } }
"markup.link.text" = "avocado-green"
"markup.quote" = "avocado-green"
"markup.raw" = "lava-gold"

# Diff
"diff.plus" = "avocado-green"
"diff.minus" = "persimmon"
"diff.delta" = "burnt-orange"

[palette]
# Primary colors
walnut = "#2A1810"
chocolate-brown = "#5F3822"
almond = "#F4DDB3"
harvest-gold = "#E9A131"
burnt-orange = "#F67422"
avocado-green = "#79966d"
denim-blue = "#5B7C99"
lava-gold = "#D3BE47"
persimmon = "#E84A38"
