# name: 'Rumpus'
# preferred_background: 2a1810
# url: https://github.com/715d/rumpus

fish_color_normal f4ddb3
fish_color_command e9a131
fish_color_keyword f67422
fish_color_quote 79966d
fish_color_redirection 6687a4
fish_color_end f67422
fish_color_error e84e3c
fish_color_param f4ddb3
fish_color_comment a07d67
fish_color_selection --background=d3be47
fish_color_search_match --background=d3be47
fish_color_operator 6687a4
fish_color_escape f1c760
fish_color_autosuggestion a07d67
fish_color_cancel e84e3c
fish_pager_color_progress 79966d
fish_pager_color_prefix e9a131
fish_pager_color_completion f4ddb3
fish_pager_color_description a07d67
fish_pager_color_selected_background --background=d3be47
